version: "3"
services:
  # web:
  #   image: nginx:latest
  #   container_name: box-billing-app
  #   volumes:
  #     - ${PWD}/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
  #     - ${PWD}/src:/var/www/html
  #     - ${PWD}/landingpage:/var/www/html/landingpage
  #   ports:
  #    - "8004:80"
  #   tty: true
  #   stdin_open: true
  #   command: [ "nginx", "-g", "daemon off;" ]
  #   networks:
  #     hostnet: {}
  # php:
  #   image: php:fpm-alpine
  #   container_name: php
  #   ports:
  #     - 9000:9000
  #   volumes:
  #     - ${PWD}/:/var/www/html
  #   working_dir:  /var/www/html/src
  #   environment:
  #     DB_HOST: database
  #     DB_NAME: boxbilling
  #     DB_USER: root
  #     DB_PASS: root
  #   tty: true
  #   stdin_open: true
  #   networks:
  #     hostnet: {}
  #   depends_on:
  #     - database
  #   restart: always
  database:
    image: mariadb
    container_name: mariadb
    ports:
      - 6033:3306
    environment:
      MARIADB_ROOT_USER: root 
      MARIADB_ROOT_PASSWORD: root
      MARIADB_ROOT_DATABASE: boxbillingdb 
    tty: true
    stdin_open: true
    networks:
      hostnet: {}
    restart: always
networks:
  hostnet:
    external: true
    name: box-billing-net

